# Default initial positions for orco2's ros2_control fake system

initial_positions:
  index: 0
  index (1): 0
  index (2): 0
  middle: 0
  middle (1): 0
  middle (2): 0
  pinky: 0
  pinky (1): 0
  pinky (2): 0
  ring: 0
  ring (1): 0
  ring (2): 0
  thumb: 0
  thumb (1): 0